# Generated by Django 3.0.2 on 2020-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic_test',
            name='statement',
            field=models.CharField(max_length=300),
        ),
    ]
